CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	names VARCHAR NOT NULL,
	username VARCHAR NOT NULL,
	password VARCHAR NOT NULL,
	created_at CHAR(19) NOT NULL,
	email VARCHAR NOT NULL,
	status VARCHAR(1) NOT NULL
);